import type {
  AspirationDef,
  CareerDef,
  ContentPack,
  InteractionDef,
  ObjectDef,
  TraitDef,
} from '@lifesim/sim';

const objects: ObjectDef[] = [
  {
    id: 'object.fridge_basic',
    nameKey: 'Fridge',
    category: 'appliances',
    price: 400,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['food_source', 'electronics'],
    outdoor: false,
    color: '#4a90d9',
    slots: [{ id: 'use_front', offset: { x: 0, y: 1 }, facing: 0, tags: ['use'], exclusive: true }],
    interactions: ['interact.fridge_snack', 'interact.fridge_start_meal'],
    states: ['default', 'open'],
  },
  {
    id: 'object.stove_basic',
    nameKey: 'Stove',
    category: 'appliances',
    price: 500,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['cooking', 'electronics', 'surface'],
    outdoor: false,
    color: '#666',
    slots: [{ id: 'use_front', offset: { x: 0, y: 1 }, facing: 0, tags: ['cook'], exclusive: true }],
    interactions: ['interact.stove_cook'],
    states: ['default'],
  },
  {
    id: 'object.counter_basic',
    nameKey: 'Counter',
    category: 'surfaces',
    price: 150,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['surface'],
    outdoor: false,
    color: '#c4a574',
    slots: [{ id: 'use_front', offset: { x: 0, y: 1 }, facing: 0, tags: ['use'], exclusive: true }],
    interactions: [],
    states: ['default'],
  },
  {
    id: 'object.table_dining',
    nameKey: 'Dining Table',
    category: 'surfaces',
    price: 300,
    footprint: { w: 2, h: 2 },
    blocksPath: true,
    tags: ['surface', 'dining'],
    outdoor: false,
    color: '#8b5a2b',
    slots: [
      { id: 'seat_0', offset: { x: 0, y: 2 }, facing: 0, tags: ['eat', 'sit'], exclusive: true },
      { id: 'seat_1', offset: { x: 1, y: 2 }, facing: 0, tags: ['eat', 'sit'], exclusive: true },
    ],
    interactions: ['interact.eat_meal'],
    states: ['default'],
  },
  {
    id: 'object.chair_dining',
    nameKey: 'Chair',
    category: 'seating',
    price: 80,
    footprint: { w: 1, h: 1 },
    blocksPath: false,
    tags: ['sit'],
    outdoor: false,
    color: '#a67c52',
    slots: [{ id: 'seat', offset: { x: 0, y: 0 }, facing: 0, tags: ['sit'], exclusive: true }],
    interactions: ['interact.sit_relax'],
    states: ['default'],
  },
  {
    id: 'object.bed_double',
    nameKey: 'Double Bed',
    category: 'bedroom',
    price: 800,
    footprint: { w: 2, h: 2 },
    blocksPath: true,
    tags: ['sleep'],
    outdoor: false,
    color: '#6b4c8a',
    slots: [
      { id: 'sleep_0', offset: { x: 0, y: 2 }, facing: 0, tags: ['sleep'], exclusive: true },
      { id: 'sleep_1', offset: { x: 1, y: 2 }, facing: 0, tags: ['sleep'], exclusive: true },
    ],
    interactions: ['interact.sleep'],
    states: ['default'],
  },
  {
    id: 'object.toilet_basic',
    nameKey: 'Toilet',
    category: 'bathroom',
    price: 250,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['bathroom'],
    outdoor: false,
    color: '#eee',
    slots: [{ id: 'use', offset: { x: 0, y: 1 }, facing: 0, tags: ['toilet'], exclusive: true }],
    interactions: ['interact.use_toilet'],
    states: ['default'],
  },
  {
    id: 'object.shower_basic',
    nameKey: 'Shower',
    category: 'bathroom',
    price: 350,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['bathroom'],
    outdoor: false,
    color: '#7ec8e3',
    slots: [{ id: 'use', offset: { x: 0, y: 1 }, facing: 0, tags: ['shower'], exclusive: true }],
    interactions: ['interact.shower'],
    states: ['default'],
  },
  {
    id: 'object.sink_basic',
    nameKey: 'Sink',
    category: 'bathroom',
    price: 120,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['bathroom'],
    outdoor: false,
    color: '#b0c4de',
    slots: [{ id: 'use', offset: { x: 0, y: 1 }, facing: 0, tags: ['wash'], exclusive: true }],
    interactions: ['interact.wash_hands'],
    states: ['default'],
  },
  {
    id: 'object.sofa_basic',
    nameKey: 'Sofa',
    category: 'living',
    price: 450,
    footprint: { w: 2, h: 1 },
    blocksPath: true,
    tags: ['sit', 'relax'],
    outdoor: false,
    color: '#2d6a4f',
    slots: [
      { id: 'seat_0', offset: { x: 0, y: 1 }, facing: 0, tags: ['sit'], exclusive: true },
      { id: 'seat_1', offset: { x: 1, y: 1 }, facing: 0, tags: ['sit'], exclusive: true },
    ],
    interactions: ['interact.sit_relax', 'interact.watch_from_sofa'],
    states: ['default'],
  },
  {
    id: 'object.tv_basic',
    nameKey: 'TV',
    category: 'electronics',
    price: 600,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['electronics', 'fun'],
    outdoor: false,
    color: '#222',
    slots: [{ id: 'watch', offset: { x: 0, y: -1 }, facing: 2, tags: ['watch'], exclusive: false }],
    interactions: ['interact.watch_tv'],
    states: ['default', 'on'],
  },
  {
    id: 'object.bookshelf',
    nameKey: 'Bookshelf',
    category: 'skill',
    price: 200,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['skill', 'logic'],
    outdoor: false,
    color: '#5c4033',
    slots: [{ id: 'use', offset: { x: 0, y: 1 }, facing: 0, tags: ['read'], exclusive: true }],
    interactions: ['interact.read_book'],
    states: ['default'],
  },
  {
    id: 'object.desk_computer',
    nameKey: 'Computer Desk',
    category: 'skill',
    price: 700,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['electronics', 'skill', 'logic'],
    outdoor: false,
    color: '#3d3d3d',
    slots: [{ id: 'use', offset: { x: 0, y: 1 }, facing: 0, tags: ['computer'], exclusive: true }],
    interactions: ['interact.use_computer'],
    states: ['default'],
  },
  {
    id: 'object.plant_pot',
    nameKey: 'Potted Plant',
    category: 'decor',
    price: 50,
    footprint: { w: 1, h: 1 },
    blocksPath: false,
    tags: ['decor'],
    outdoor: true,
    color: '#228b22',
    slots: [],
    interactions: [],
    states: ['default'],
  },
  {
    id: 'object.coffee_table',
    nameKey: 'Coffee Table',
    category: 'living',
    price: 180,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['surface'],
    outdoor: false,
    color: '#a0522d',
    slots: [],
    interactions: [],
    states: ['default'],
  },
  {
    id: 'object.dresser',
    nameKey: 'Dresser',
    category: 'bedroom',
    price: 220,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['storage'],
    outdoor: false,
    color: '#8b4513',
    slots: [],
    interactions: [],
    states: ['default'],
  },
  {
    id: 'object.lamp_floor',
    nameKey: 'Floor Lamp',
    category: 'decor',
    price: 90,
    footprint: { w: 1, h: 1 },
    blocksPath: false,
    tags: ['decor', 'electronics'],
    outdoor: false,
    color: '#f4d03f',
    slots: [],
    interactions: [],
    states: ['default'],
  },
  {
    id: 'object.exercise_mat',
    nameKey: 'Exercise Mat',
    category: 'skill',
    price: 60,
    footprint: { w: 1, h: 1 },
    blocksPath: false,
    tags: ['fitness'],
    outdoor: false,
    color: '#e74c3c',
    slots: [{ id: 'use', offset: { x: 0, y: 0 }, facing: 0, tags: ['exercise'], exclusive: true }],
    interactions: ['interact.exercise'],
    states: ['default'],
  },
  {
    id: 'object.easel',
    nameKey: 'Easel',
    category: 'skill',
    price: 280,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['creativity'],
    outdoor: false,
    color: '#e67e22',
    slots: [{ id: 'use', offset: { x: 0, y: 1 }, facing: 0, tags: ['paint'], exclusive: true }],
    interactions: ['interact.paint'],
    states: ['default'],
  },
  {
    id: 'object.stereo',
    nameKey: 'Stereo',
    category: 'electronics',
    price: 320,
    footprint: { w: 1, h: 1 },
    blocksPath: true,
    tags: ['fun', 'electronics'],
    outdoor: false,
    color: '#9b59b6',
    slots: [{ id: 'use', offset: { x: 0, y: 1 }, facing: 0, tags: ['dance'], exclusive: false }],
    interactions: ['interact.dance'],
    states: ['default'],
  },
  // More catalog fillers to approach 40
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `object.decor_${i + 1}`,
    nameKey: `Decor Item ${i + 1}`,
    category: 'decor',
    price: 40 + i * 10,
    footprint: { w: 1, h: 1 },
    blocksPath: false,
    tags: ['decor'],
    outdoor: i % 3 === 0,
    color: `hsl(${(i * 37) % 360} 50% 50%)`,
    slots: [] as ObjectDef['slots'],
    interactions: [] as string[],
    states: ['default'],
  })),
];

const interactions: InteractionDef[] = [
  {
    id: 'interact.fridge_snack',
    nameKey: 'Grab snack',
    durationTicks: 8,
    slotTag: 'use',
    outcomes: { needs: { hunger: 15 }, setObjectState: 'default' },
    autonomyWeight: 1,
    ads: { hunger: 1.2 },
  },
  {
    id: 'interact.fridge_start_meal',
    nameKey: 'Get ingredients',
    durationTicks: 10,
    slotTag: 'use',
    outcomes: {
      giveHeldItem: 'item.ingredients',
      setObjectState: 'open',
    },
    chain: {
      nextInteractionId: 'interact.stove_cook',
      requireSurfaceTags: ['cooking'],
    },
    autonomyWeight: 1.5,
    ads: { hunger: 1.5 },
  },
  {
    id: 'interact.stove_cook',
    nameKey: 'Cook meal',
    durationTicks: 25,
    slotTag: 'cook',
    requires: { heldItem: 'item.ingredients' },
    outcomes: {
      clearHeldItem: true,
      giveHeldItem: 'item.meal',
      skillXp: { cooking: 25 },
      setCrafting: {
        chainId: 'cook_meal',
        stageId: 'cooked',
        ticksRemaining: 0,
        outputHeldItem: 'item.meal',
      },
    },
    chain: {
      nextInteractionId: 'interact.eat_meal',
      requireSurfaceTags: ['dining'],
    },
    autonomyWeight: 1.2,
    ads: { hunger: 1.4 },
  },
  {
    id: 'interact.eat_meal',
    nameKey: 'Eat meal',
    durationTicks: 20,
    slotTag: 'eat',
    requires: { heldItem: 'item.meal' },
    outcomes: {
      needs: { hunger: 45, fun: 5 },
      clearHeldItem: true,
      clearCrafting: true,
      moodBuff: { id: 'well_fed', amount: 10, durationTicks: 120 },
    },
    autonomyWeight: 2,
    ads: { hunger: 2 },
  },
  {
    id: 'interact.sleep',
    nameKey: 'Sleep',
    durationTicks: 90,
    slotTag: 'sleep',
    outcomes: { needs: { energy: 70, bladder: -5 } },
    autonomyWeight: 2,
    ads: { energy: 2.5 },
  },
  {
    id: 'interact.use_toilet',
    nameKey: 'Use toilet',
    durationTicks: 12,
    slotTag: 'toilet',
    outcomes: { needs: { bladder: 80 } },
    autonomyWeight: 3,
    ads: { bladder: 3 },
  },
  {
    id: 'interact.shower',
    nameKey: 'Shower',
    durationTicks: 20,
    slotTag: 'shower',
    outcomes: { needs: { hygiene: 80, energy: 5 } },
    autonomyWeight: 1.5,
    ads: { hygiene: 2 },
  },
  {
    id: 'interact.wash_hands',
    nameKey: 'Wash hands',
    durationTicks: 6,
    slotTag: 'wash',
    outcomes: { needs: { hygiene: 15 } },
    autonomyWeight: 0.5,
    ads: { hygiene: 0.8 },
  },
  {
    id: 'interact.sit_relax',
    nameKey: 'Sit & relax',
    durationTicks: 30,
    slotTag: 'sit',
    outcomes: { needs: { fun: 15, energy: 8 } },
    autonomyWeight: 0.8,
    ads: { fun: 0.8, energy: 0.5 },
  },
  {
    id: 'interact.watch_tv',
    nameKey: 'Watch TV',
    durationTicks: 40,
    outcomes: { needs: { fun: 30 }, setObjectState: 'on', skillXp: { creativity: 5 } },
    autonomyWeight: 1,
    ads: { fun: 1.5 },
  },
  {
    id: 'interact.watch_from_sofa',
    nameKey: 'Watch from sofa',
    durationTicks: 40,
    slotTag: 'sit',
    outcomes: { needs: { fun: 25, energy: 5 } },
    autonomyWeight: 1,
    ads: { fun: 1.3 },
  },
  {
    id: 'interact.read_book',
    nameKey: 'Read',
    durationTicks: 35,
    slotTag: 'read',
    outcomes: { needs: { fun: 10 }, skillXp: { logic: 30 } },
    autonomyWeight: 0.7,
    ads: { fun: 0.5 },
  },
  {
    id: 'interact.use_computer',
    nameKey: 'Use computer',
    durationTicks: 40,
    slotTag: 'computer',
    outcomes: {
      needs: { fun: 15, social: -5 },
      skillXp: { logic: 20, charisma: 10 },
    },
    autonomyWeight: 0.9,
    ads: { fun: 0.7 },
  },
  {
    id: 'interact.exercise',
    nameKey: 'Exercise',
    durationTicks: 35,
    slotTag: 'exercise',
    outcomes: {
      needs: { energy: -15, fun: 10, hygiene: -10 },
      skillXp: { fitness: 35 },
    },
    autonomyWeight: 0.6,
  },
  {
    id: 'interact.paint',
    nameKey: 'Paint',
    durationTicks: 45,
    slotTag: 'paint',
    outcomes: { needs: { fun: 25 }, skillXp: { creativity: 40 } },
    autonomyWeight: 0.7,
    ads: { fun: 1 },
  },
  {
    id: 'interact.dance',
    nameKey: 'Dance',
    durationTicks: 25,
    outcomes: { needs: { fun: 35, energy: -10, social: 5 } },
    autonomyWeight: 0.8,
    ads: { fun: 1.4 },
  },
  // Social
  {
    id: 'interact.chat',
    nameKey: 'Chat',
    durationTicks: 20,
    social: true,
    outcomes: {
      needs: { social: 25, fun: 10 },
      relationship: { friendship: 8 },
      skillXp: { charisma: 10 },
    },
    autonomyWeight: 1.2,
    ads: { social: 1.5 },
  },
  {
    id: 'interact.joke',
    nameKey: 'Tell joke',
    durationTicks: 15,
    social: true,
    outcomes: {
      needs: { social: 15, fun: 20 },
      relationship: { friendship: 5 },
    },
    autonomyWeight: 1,
    ads: { social: 1, fun: 0.8 },
  },
  {
    id: 'interact.flirt',
    nameKey: 'Flirt',
    durationTicks: 18,
    social: true,
    outcomes: {
      needs: { social: 20, fun: 15 },
      relationship: { friendship: 3, romance: 10 },
    },
    autonomyWeight: 0.6,
    ads: { social: 1 },
  },
  {
    id: 'interact.mean',
    nameKey: 'Be mean',
    durationTicks: 12,
    social: true,
    outcomes: {
      needs: { social: 5, fun: 10 },
      relationship: { friendship: -12 },
    },
    autonomyWeight: 0.2,
  },
];

const careers: CareerDef[] = [
  {
    id: 'career.office_worker',
    nameKey: 'Office Worker',
    schedule: { startMinute: 9 * 60, endMinute: 17 * 60, days: [0, 1, 2, 3, 4] },
    levels: [
      { titleKey: 'Mailroom Clerk', payPerDay: 120 },
      { titleKey: 'Assistant', payPerDay: 180, requiredSkill: { id: 'charisma', min: 1 } },
      { titleKey: 'Associate', payPerDay: 260, requiredSkill: { id: 'logic', min: 2 } },
      { titleKey: 'Manager', payPerDay: 380, requiredSkill: { id: 'charisma', min: 4 } },
      { titleKey: 'Director', payPerDay: 520, requiredSkill: { id: 'logic', min: 5 } },
    ],
  },
  {
    id: 'career.chef',
    nameKey: 'Chef',
    schedule: { startMinute: 14 * 60, endMinute: 22 * 60, days: [0, 1, 2, 3, 4, 5] },
    levels: [
      { titleKey: 'Dishwasher', payPerDay: 100 },
      { titleKey: 'Line Cook', payPerDay: 160, requiredSkill: { id: 'cooking', min: 1 } },
      { titleKey: 'Sous Chef', payPerDay: 240, requiredSkill: { id: 'cooking', min: 3 } },
      { titleKey: 'Head Chef', payPerDay: 360, requiredSkill: { id: 'cooking', min: 5 } },
      { titleKey: 'Celebrity Chef', payPerDay: 500, requiredSkill: { id: 'cooking', min: 7 } },
    ],
  },
];

const traits: TraitDef[] = [
  {
    id: 'trait.cheerful',
    nameKey: 'Cheerful',
    needDecayMult: { fun: 0.8 },
    autonomyBias: { 'interact.joke': 1.5 },
  },
  {
    id: 'trait.foodie',
    nameKey: 'Foodie',
    needDecayMult: { hunger: 1.2 },
    autonomyBias: { 'interact.fridge_start_meal': 2 },
  },
  {
    id: 'trait.neat',
    nameKey: 'Neat',
    needDecayMult: { hygiene: 1.15 },
  },
  {
    id: 'trait.lazy',
    nameKey: 'Lazy',
    needDecayMult: { energy: 1.2 },
    autonomyBias: { 'interact.sit_relax': 2, 'interact.exercise': 0.2 },
  },
  {
    id: 'trait.outgoing',
    nameKey: 'Outgoing',
    needDecayMult: { social: 1.25 },
    autonomyBias: { 'interact.chat': 2 },
  },
  {
    id: 'trait.genius',
    nameKey: 'Genius',
    autonomyBias: { 'interact.read_book': 1.8, 'interact.use_computer': 1.5 },
  },
];

const aspirations: AspirationDef[] = [
  {
    id: 'aspiration.friendly',
    nameKey: 'Friend of the World',
    milestones: [
      { id: 'm1', descriptionKey: 'Socialize often', target: 20 },
      { id: 'm2', descriptionKey: 'Make connections', target: 50 },
    ],
  },
  {
    id: 'aspiration.master_chef',
    nameKey: 'Master Chef',
    milestones: [
      { id: 'm1', descriptionKey: 'Cook and eat meals', target: 15 },
      { id: 'm2', descriptionKey: 'Kitchen mastery', target: 40 },
    ],
  },
  {
    id: 'aspiration.career_minded',
    nameKey: 'Big Career',
    milestones: [
      { id: 'm1', descriptionKey: 'Work days', target: 10 },
      { id: 'm2', descriptionKey: 'Climb the ladder', target: 30 },
    ],
  },
];

export function loadBuiltinContent(): ContentPack {
  return { objects, interactions, careers, traits, aspirations };
}

export const BODY_PRESETS = ['body_a', 'body_b'];
export const HAIR_PRESETS = ['hair_short', 'hair_long', 'hair_curly'];
export const OUTFIT_PRESETS = ['outfit_casual', 'outfit_pro', 'outfit_sport'];
export const SKIN_TONES = ['tone_1', 'tone_2', 'tone_3', 'tone_4', 'tone_5'];
