import type { NpcDef } from '@lifesim/sim';

/**
 * Town roster — neighbors + public hangouts.
 * Player household sims are separate; these never join memberIds.
 */
export const NPCS: NpcDef[] = [
  {
    id: 'npc.mei_chen',
    firstName: 'Mei',
    lastName: 'Chen',
    bio: 'Keeps the Chen house spotless and always has a book nearby.',
    traits: ['trait.neat', 'trait.genius'],
    aspirationId: 'aspiration.career_minded',
    visual: {
      bodyPreset: 'body_b',
      hairPreset: 'hair_long',
      outfitPreset: 'outfit_pro',
      skinTone: 'tone_2',
    },
    homePlaceId: 'house_chen',
    startPlaceId: 'house_chen',
    spawnOffset: { x: -1, y: -2 },
  },
  {
    id: 'npc.wei_chen',
    firstName: 'Wei',
    lastName: 'Chen',
    bio: 'Loves cooking loud dinners and chatting with whoever walks in.',
    traits: ['trait.foodie', 'trait.outgoing'],
    aspirationId: 'aspiration.master_chef',
    visual: {
      bodyPreset: 'body_a',
      hairPreset: 'hair_short',
      outfitPreset: 'outfit_casual',
      skinTone: 'tone_2',
    },
    homePlaceId: 'house_chen',
    startPlaceId: 'house_chen',
    spawnOffset: { x: 1, y: -2 },
  },
  {
    id: 'npc.sofia_park',
    firstName: 'Sofia',
    lastName: 'Park',
    bio: 'Neighborhood optimist — usually found outside if the weather is decent.',
    traits: ['trait.cheerful', 'trait.outgoing'],
    aspirationId: 'aspiration.friendly',
    visual: {
      bodyPreset: 'body_b',
      hairPreset: 'hair_curly',
      outfitPreset: 'outfit_sport',
      skinTone: 'tone_3',
    },
    homePlaceId: 'house_park',
    startPlaceId: 'park',
    spawnOffset: { x: 0, y: 0 },
  },
  {
    id: 'npc.minjun_park',
    firstName: 'Minjun',
    lastName: 'Park',
    bio: 'Would rather nap and snack than leave the sofa — unless snacks run out.',
    traits: ['trait.lazy', 'trait.foodie'],
    aspirationId: 'aspiration.master_chef',
    visual: {
      bodyPreset: 'body_a',
      hairPreset: 'hair_short',
      outfitPreset: 'outfit_casual',
      skinTone: 'tone_3',
    },
    homePlaceId: 'house_park',
    startPlaceId: 'house_park',
    spawnOffset: { x: 0, y: -3 },
  },
  {
    id: 'npc.amara_okonkwo',
    firstName: 'Amara',
    lastName: 'Okonkwo',
    bio: 'Sharp, organized, and quietly competitive about skill goals.',
    traits: ['trait.genius', 'trait.neat'],
    aspirationId: 'aspiration.career_minded',
    visual: {
      bodyPreset: 'body_b',
      hairPreset: 'hair_long',
      outfitPreset: 'outfit_pro',
      skinTone: 'tone_5',
    },
    homePlaceId: 'house_okonkwo',
    startPlaceId: 'house_okonkwo',
    spawnOffset: { x: -1, y: -2 },
  },
  {
    id: 'npc.kwame_okonkwo',
    firstName: 'Kwame',
    lastName: 'Okonkwo',
    bio: 'Warm host energy — remembers everyone\'s name on the block.',
    traits: ['trait.outgoing', 'trait.cheerful'],
    aspirationId: 'aspiration.friendly',
    visual: {
      bodyPreset: 'body_a',
      hairPreset: 'hair_curly',
      outfitPreset: 'outfit_casual',
      skinTone: 'tone_5',
    },
    homePlaceId: 'house_okonkwo',
    startPlaceId: 'house_okonkwo',
    spawnOffset: { x: 1, y: -2 },
  },
  {
    id: 'npc.lucia_diaz',
    firstName: 'Lucia',
    lastName: 'Diaz',
    bio: 'Creative spirit who hangs around the plaza sketching people.',
    traits: ['trait.cheerful', 'trait.foodie'],
    aspirationId: 'aspiration.friendly',
    visual: {
      bodyPreset: 'body_b',
      hairPreset: 'hair_long',
      outfitPreset: 'outfit_casual',
      skinTone: 'tone_4',
    },
    homePlaceId: 'house_diaz',
    startPlaceId: 'plaza',
    spawnOffset: { x: 2, y: 0 },
  },
  {
    id: 'npc.mateo_diaz',
    firstName: 'Mateo',
    lastName: 'Diaz',
    bio: 'Gym regular who will cheerfully challenge you to keep up.',
    traits: ['trait.outgoing', 'trait.cheerful'],
    aspirationId: 'aspiration.career_minded',
    visual: {
      bodyPreset: 'body_a',
      hairPreset: 'hair_short',
      outfitPreset: 'outfit_sport',
      skinTone: 'tone_4',
    },
    homePlaceId: 'house_diaz',
    startPlaceId: 'gym',
    spawnOffset: { x: 0, y: -1 },
  },
  {
    id: 'npc.nora_blake',
    firstName: 'Nora',
    lastName: 'Blake',
    bio: 'Cafe regular turned unofficial barista — knows every order by heart.',
    traits: ['trait.outgoing', 'trait.cheerful'],
    aspirationId: 'aspiration.friendly',
    visual: {
      bodyPreset: 'body_b',
      hairPreset: 'hair_curly',
      outfitPreset: 'outfit_pro',
      skinTone: 'tone_1',
    },
    homePlaceId: 'cafe',
    startPlaceId: 'cafe',
    spawnOffset: { x: -2, y: -2 },
  },
  {
    id: 'npc.theo_reed',
    firstName: 'Theo',
    lastName: 'Reed',
    bio: 'Quiet librarian type who opens up once you ask the right question.',
    traits: ['trait.genius', 'trait.neat'],
    aspirationId: 'aspiration.career_minded',
    visual: {
      bodyPreset: 'body_a',
      hairPreset: 'hair_long',
      outfitPreset: 'outfit_pro',
      skinTone: 'tone_1',
    },
    homePlaceId: 'library',
    startPlaceId: 'library',
    spawnOffset: { x: 1, y: -2 },
  },
];
